# Generated by Django 2.1.2 on 2019-02-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('dob', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=30)),
                ('phone_no', models.IntegerField()),
            ],
        ),
    ]
